### ISSUE TITLE
Get on leadership board for Contest 1

### ISSUE THREAD

**Issue by LarryBattleWork** [LarryBattleWork/Kaggle_Contest#1]
## Tasks
- [x] Setup Tensorflow 
- [ ] Get Julia kNN Benchmark working
- [ ] Get Julia Random Forest Benchmark working
- [ ] Get the MNIST example to working with detecting 0 - 9 digits.
- [ ] Use the same code to detect 0 - 9 only using the digits from the training set
- [ ] Submit

**Comment by LarryBattleWork** [comment]
[x] Setup Tensorflow: 
- Use docker to install. `docker run -it -P gcr.io/tensorflow/tensorflow /bin/bash`
From : https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html#docker-installation

**Comment by LarryBattleWork** [comment]
Contest is over.
